spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT&nullCatalogMeansCurrent=true
#    url: jdbc:mysql://localhost:3306/user_center
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=UTC
    hikari:
      username: root
      password: root123456
      # connector version >= 6.x com.mysql.jdbc.Driver
      #  connector version <= 5. x  com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        指定集群名称
        cluster-name: BJ
        metadata:
          version: 1.0
        namespace: 87980947-d66c-4ee5-a8b0-3b17222c464d
  #        cluster-name: NJ
  application:
    name: user-center
server:
  port: 8081
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    #    小坑：必须指定group
    group: test-group
