spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT&nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: root123456
      # connector version >= 6.x com.mysql.jdbc.Driver
      #  connector version <= 5.x  com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver