spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT&nullCatalogMeansCurrent=true
    #    url: jdbc:mysql://localhost:3306/user_center
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT
    hikari:
      username: root
      password: root123456
      # connector version >= 6.x com.mysql.jdbc.Driver
      #  connector version <= 5. x  com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #        指定集群名称
        cluster-name: BJ
        namespace: 87980947-d66c-4ee5-a8b0-3b17222c464d
        metadata:
          version: 1.0
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: add-bonus
          #          如果用的rocketmq，一定要设置
          #          如果是其他mq可留空
          group: binder-group
  application:
    name: user-center
  zipkin:
    base-url: http://localhost:9411/
#    discovery-client-enabled: false
    discoveryClientEnabled: false
  sleuth:
    sampler:
      #抽样率，默认是0.1（10%）
      probability: 1.0
server:
  port: 8081
logging:
  level:
    com.alibaba.nacos: error
    com.springframework.cloud.sleuth: debug
jwt:
  secret: asdasdasdadadsada
  # 有效期 单位秒 默认2周
  expire-time-in-second: 1209600